command:
  - /bin/sh
  - -c
  - "gunicorn -w 2 -b 0.0.0.0:${DATABRICKS_APP_PORT} app:app"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: DATABRICKS_CATALOG
    value: "tim-kreutzfeldt-test"
  - name: DATABRICKS_SCHEMA
    value: "adsb"
